### ISSUE TITLE
gonawin admins should have the ability to specify if a tournament is the official

### ISSUE THREAD

**Issue by rjourde** [taironas/gonawin#400]
- Add boolean in tournament entity
 - By default a newly created tournament is unofficial
 - In tournament edit page, admins have the ability to validate a tournament
 - Add specific icon (official) on tournament card (ng#/tournaments) and on tournament page (ng#/tournaments/:id)

**Comment by santiaago** [comment]
At the moment all tournaments are created by us, when creation of tournaments can be created by anyone we'll reconsider this
