### ISSUE TITLE
Extract client controller into its own file

### ISSUE THREAD

**Issue by rjourde** [taironas/gonawin#621]

**Comment by rjourde** [comment]
I don't remember the purpose of this issue. If you don't remember too, I'll close it.

**Comment by santiaago** [comment]
I think it was to have a file per ng-controller instead of a single file for all controllers.

**Comment by rjourde** [comment]
yes right. Good. We keep it.

**Comment by santiaago** [comment]
this will not be done, plus when we will migrate to Angular2 we will do this.
