### ISSUE TITLE
only create one request invitation

### ISSUE THREAD

**Issue by santiaago** [taironas/gonawin#649]

**Comment by rjourde** [comment]
Do you have a test case?

I don't see how I can reproduce this because the button is disabled after requesting an invitation.

**Comment by santiaago** [comment]
User can ask to join a team multiple times. I think that is how you get that issue

**Comment by rjourde** [comment]
User will be able to request again an invitation after the current one has been denied.

**Comment by santiaago** [comment]
can you force (try to create another request) the controller should not create a new request if one already exist and has not been handled.

**Comment by rjourde** [comment]
Yes I agree. I can try to force another request.

**Comment by santiaago** [comment]
:+1:

**Comment by rjourde** [comment]
PR merged and deployed.
