### ISSUE TITLE
consistent errors

### ISSUE THREAD

**Issue by santiaago** [taironas/gonawin#752]
prefer `fmt.Errorf( "my error %v", err)`
to `errors.New(fmt.Sprintf("my error %v", err))`

https://github.com/taironas/gonawin/search?utf8=%E2%9C%93&q=errors.New%28fmt.Sprintf

**Comment by rjourde** [comment]
71 occurrences to replace in 12 files

**Comment by santiaago** [comment]
looks good

**Comment by rjourde** [comment]
Pr merged.
