### ISSUE TITLE
test User.ContainsTournamentId

### ISSUE THREAD

**Issue by rjourde** [taironas/gonawin#780]

**Comment by rjourde** [comment]
After looking at User.ContainsTournamentId, I found many similar methods or functions like this one. I would like to add a contain function : `func Contain(s []int64, value int64) (bool, int)` or method `func (s []int64) Contain(value int64) (bool, int)` into helpers/slice.go

What do you think ?

**Comment by santiaago** [comment]
I am not against it - make the PR and we will have a look

**Comment by rjourde** [comment]
PR merged.
