### ISSUE TITLE
inconsistency regarding team's properties between /j/users/:userId/teams and /j/teams

### ISSUE THREAD

**Issue by rjourde** [taironas/gonawin#818]
For Team entity define mandatory properties and set the others as optionals.

Proposal for mandatory properties:
- Id
- Name
- MembersCount
- IsPrivate
- ImageURL

optionals:
- Description
- Accuracy
- Joined
- Members
- Tournaments

the array of teams should be under a `Teams` JSON node. Only /j/users/:userId/teams is doing it.

**Comment by rjourde** [comment]
@santiaago Could you review this?

**Comment by santiaago** [comment]
ok with this
